# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DV', 'Delegiertenversammlung'), ('SEKO', 'Sektionskonferenz'), ('JV', 'Jahresversammlung'), ('BV', 'Bildungsveranstaltung')], max_length=10, verbose_name='Kategorie')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('location', models.CharField(max_length=100, verbose_name='Ort')),
                ('date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer*in')),
            ],
            options={
                'verbose_name': 'Versammlung',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G+', 'Richtig gegendert'), ('G-', 'Falsch gegendert'), ('UB', 'Unterbrechung'), ('EX', 'Ende')], max_length=3, verbose_name='Kategorie')),
                ('gender', models.CharField(choices=[('f', 'Frau'), ('m', 'Mann'), ('a', 'Anderes')], max_length=2, verbose_name='Gender')),
                ('position', models.CharField(choices=[('GL', 'Geschäftsleitung'), ('BA', 'Basis'), ('GA', 'Gäste'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ereignis',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('f', 'Frau'), ('m', 'Mann'), ('a', 'Anderes')], max_length=2, verbose_name='Gender')),
                ('position', models.CharField(blank=True, choices=[('GL', 'Geschäftsleitung'), ('BA', 'Basis'), ('GA', 'Gäste'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position')),
                ('category', models.CharField(blank=True, choices=[('OR', 'Organisatorisch'), ('IH', 'Inhaltlich')], max_length=2, verbose_name='Kategorie')),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genderwatch.Assembly', verbose_name='Versammlung')),
            ],
            options={
                'verbose_name': 'Wortmeldung',
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genderwatch.Verdict', verbose_name='Wortmeldung'),
        ),
    ]
