# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genderwatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='user',
        ),
        migrations.AddField(
            model_name='assembly',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Benutzer*in'),
        ),
    ]
