# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genderwatch', '0002_auto_20170723_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='protokolliert von'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assembly',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Prtokollierende'),
        ),
    ]
