# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0004_auto_20170724_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Männer*'), ('f', 'Frauen*'), ('a', 'Andere')], max_length=2, verbose_name='Gender')),
                ('count', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['count'],
            },
        ),
        migrations.AlterField(
            model_name='assembly',
            name='category',
            field=models.CharField(choices=[('DV', 'Delegiertenversammlung'), ('SEKO', 'Sektionskonferenz'), ('JV', 'Jahresversammlung'), ('BV', 'Bildungsveranstaltung'), ('PT', 'Parteitag')], max_length=10, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('G+', 'Richtig gegendert'), ('G-', 'Falsch gegendert'), ('UB', 'Unterbrechung'), ('SX', 'Sexismus'), ('EX', 'Ende')], max_length=3, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='position',
            field=models.CharField(choices=[('GL', 'Geschäftsleitung'), ('BA', 'Basis'), ('DG', 'Delegierte'), ('GA', 'Gäst*innen'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='position',
            field=models.CharField(blank=True, choices=[('GL', 'Geschäftsleitung'), ('BA', 'Basis'), ('DG', 'Delegierte'), ('GA', 'Gäst*innen'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='participant',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genderwatch.Assembly'),
        ),
    ]
