# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0005_auto_20170805_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='positions',
            field=models.CharField(default='GL,DG', max_length=100, verbose_name='Positionen'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Anzahl'),
        ),
    ]
