# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0006_auto_20170805_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='topics',
            field=models.TextField(default='OR, Organisatorisch\nPO, Politisch', verbose_name='Themen'),
        ),
    ]
