# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0007_assembly_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(blank=True, choices=[('FE', 'Feminismus'), ('DI', 'Digitalisierung'), ('VE', 'Venezuela'), ('99', '99%-Initiative'), ('MI', 'Migration'), ('OR', 'Organisatorisch'), ('WI', 'Wirtschaft'), ('FI', 'Finanzen'), ('UW', 'Umwelt'), ('CA', 'Care'), ('AR', 'Arbeit'), ('ST', 'Staat')], max_length=2, verbose_name='Kategorie'),
        ),
    ]
