# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0008_auto_20170930_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(blank=True, max_length=2, verbose_name='Kategorie'),
        ),
    ]
