# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderwatch', '0009_auto_20171013_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='topics',
            field=models.TextField(default='Begrüssung\nTraktandum 1', verbose_name='Themen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='position',
            field=models.CharField(choices=[('GL', 'Geschäftsleitung'), ('VS', 'Vorstand'), ('BA', 'Basis'), ('DG', 'Delegierte'), ('GA', 'Gäst*innen'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(blank=True, max_length=140, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='position',
            field=models.CharField(blank=True, choices=[('GL', 'Geschäftsleitung'), ('VS', 'Vorstand'), ('BA', 'Basis'), ('DG', 'Delegierte'), ('GA', 'Gäst*innen'), ('PO', 'Podium'), ('WS', 'Workshopleitung')], max_length=2, verbose_name='Position'),
        ),
    ]
